# function to change user input of Rock, Paper or Scissors into a corresponding number, so it can be compared with a random number generated by computer
def rock_paper_scissors(word):
    if word == "Rock":
        return 1
    elif word == "Paper":
        return 2
    elif word == "Scissors":
        return 3
